name: 02 - Workflows Event
on: 
  push:
  pull_request:
  schedule: 
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  Build-job:
    runs-on: ubuntu-latest 
    steps:
      - name: Show trigger
        run: echo "valor del event_name ${{github.event_name}}"
