name: 13 - Using- Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute cache steps
        type: boolean
        default: true 
      node-version:
        type: choice  
        options:
          - 18.x
          - 20.x
          - 21.x
        default: '20.x'
jobs:
  build:
    defaults:
      run:
        working-directory:  13-caching/react-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Node
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '{{ inputs.node-version }}'
      - name: Download dependency
        uses: actions/cache@v3
        if: ${{ inputs.use-cache }}
        id: cache
        with:
          path: 13-caching/react-app/node_modelues
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Building  
        run: npm run build