name: 14 - Working with artifacts
on: 
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory:  14-artifacts/react-app
    steps:
      - name: Checkout Node
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Download dependency
        uses: actions/cache@v3
        id: cache
        with:
          path: 14-artifacts/react-app/node_modules
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
      - name: Install dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Unit Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: app
          path: 14-artifacts/react-app/build
  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          name: app 
          path: build
      - name: Show Folder structure  
        run: ls -R