name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true #(true) por defecto si un job de la matrix falla , los demas steps fallaran. (false) aunque falle un steps los demas se ejecutan.
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
        node: 
          - 18.x
          - 20.x
          - 21.x
        include:
          - os: ubuntu-latest
            node: 16.x
          - os: ubuntu-latest
            node: 21.x
            tag: experimental
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Experimental fail
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Perform some tests
        run: echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [blue, red]
        shape: [circle,square]
        size: [small, medium ]
        include:
          - color: red
            opacity: 90
          - shape: circle
            opacity: 80
          - color: red  
            shape: triangle
          - opacity: 50
          - color: red
            shape: circle 
            circle: large
        exclude:
          - color: red
            shape: circle
    steps:
      - name: Dummy steps 
        run: echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
