name: 17 - Custom Actions - Composite
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 17-custom-actions/react-app
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS NPM dependencies
        uses: ./.github/actions/compiste-cache-deps
        with:
          node-version: 20.x
          working-dir: 17-custom-actions/react-app
      - name: Test
        run: npm run test
        
      - name: Build
        run: npm run build
        working-directory: 17-custom-actions/react-app
      - name: Test
        run: npm run test
        working-directory: 17-custom-actions/react-app