name: 18-1-reusable-workflows.yaml
on: 
  workflow_call:
    outputs:
      my-output:
        value: ${{ jobs.Build.outputs.path-output }}
        
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      path-output: ${{ steps.url.outputs.path }}
    steps:
      - name: echo to variable
        id: url
        run: |
          # Do something
          echo "path=https://google.es" >> "$GITHUB_OUTPUT"