name: 18-1-reusable-workflows.yaml
on: 
  workflow_call:
    outputs:
      my-output:
        value: ${{ jobs.Build.outputs.path-output }}
        
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      path-output: ${{ steps.my-step.outputs.path }}
    steps:
      - name: My Step
        id: my-step
        run: |
          # Do something
          echo "path=my-value" >> "$GITHUB_OUTPUT"